[project]
name = "user-details"
version = "0.1.0"
description = "Simple project with sql alcamy"
readme = "README.md"
authors = [
    { name = "yagna", email = "yagna247@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.44",
]

[project.scripts]
user-details = "user_details:main"

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"
